### ISSUE TITLE
Assign shortcuts based on file name

### ISSUE THREAD

**Issue by wenlzhang** [Vinzent03/obsidian-shortcuts-for-starred-files#3]
Is it possible to assign shortcuts based on file name, instead of the order of the starred files, as sometimes one may adjust the order of the starred files? For instance, the `Shortcut A` is for `Note A`, whether it's the first or the last starred file in the list.

**Comment by Vinzent03** [comment]
My goal with this plugin was to open specific files via hotkey. An easy way to accomplish this was with the core plugin `star`. When you want it without the order of starred files, it would mean you have to set these in the settings. But this would result in a new plugin, because it has nothing to do with starred files anymore.

**Comment by Vinzent03** [comment]
If I get the design, to choose which file to open, to work. The plugin should not be a problem.

**Comment by wenlzhang** [comment]
That's good to know. Looking forward to that!

**Comment by Vinzent03** [comment]
New plugin is finished. I am just waiting for the pull request to add it to the store. If you want to test it out, install it via GitHub method: https://github.com/Vinzent03/obsidian-hotkeys-for-specific-files#from-github . Let me know if you face any issues.
